/**
 * Farm Planner — Season Plans and Tasks
 *
 * Phase 0: Schema in place. All handlers are stubs.
 * Phase 3 will fill these in.
 *
 * Key design:
 * - Season plan linked to a cost template auto-generates tasks via weekFromStart
 * - Tasks with recurrence != "none" auto-create next task on completion
 * - All queries offline-safe (useOfflineQuery compatible)
 */

import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import { Id } from "./_generated/dataModel";
import { getUgandaTime } from "./utils";

// ─── SEASON PLANS ────────────────────────────────────────────────────────────

/** List farmer's season plans */
export const listSeasonPlans = query({
  args: {
    farmerId: v.id("users"),
    status: v.optional(v.union(
      v.literal("planning"),
      v.literal("active"),
      v.literal("completed"),
      v.literal("abandoned")
    )),
  },
  handler: async (ctx, args) => {
    if (args.status) {
      return await ctx.db
        .query("farmSeasonPlans")
        .withIndex("by_farmer_status", (q: any) => q.eq("farmerId", args.farmerId).eq("status", args.status))
        .order("desc")
        .collect();
    }
    return await ctx.db
      .query("farmSeasonPlans")
      .withIndex("by_farmer", (q: any) => q.eq("farmerId", args.farmerId))
      .order("desc")
      .collect();
  },
});

/** Create a season plan. If linkedCostTemplateId provided, auto-generate tasks. */
export const createSeasonPlan = mutation({
  args: {
    farmerId: v.id("users"),
    planName: v.string(),
    category: v.union(v.literal("crop"), v.literal("livestock")),
    cropOrLivestockType: v.string(),
    emoji: v.optional(v.string()),
    startDate: v.number(),
    expectedHarvestDate: v.number(),
    acresCovered: v.optional(v.number()),
    linkedCostTemplateId: v.optional(v.id("cropCostTemplates")),
    linkedLivestockCostTemplateId: v.optional(v.id("livestockCostTemplates")),
    notes: v.optional(v.string()),
  },
  handler: async (ctx, args): Promise<Id<"farmSeasonPlans">> => {
    const now = getUgandaTime();
    const planId = await ctx.db.insert("farmSeasonPlans", {
      farmerId: args.farmerId,
      planName: args.planName,
      category: args.category,
      cropOrLivestockType: args.cropOrLivestockType,
      emoji: args.emoji,
      startDate: args.startDate,
      expectedHarvestDate: args.expectedHarvestDate,
      acresCovered: args.acresCovered,
      linkedCostTemplateId: args.linkedCostTemplateId,
      linkedLivestockCostTemplateId: args.linkedLivestockCostTemplateId,
      status: "planning",
      notes: args.notes,
      createdAt: now,
      updatedAt: now,
    });

    // Auto-generate tasks from linked cost template stages
    if (args.linkedCostTemplateId) {
      const template = await ctx.db.get(args.linkedCostTemplateId);
      if (template) {
        for (const stage of template.stages) {
          const dueDate = args.startDate + stage.weekFromStart * 7 * 24 * 60 * 60 * 1000;
          await ctx.db.insert("farmPlannerTasks", {
            farmerId: args.farmerId,
            seasonPlanId: planId,
            taskName: stage.stageName,
            emoji: stage.emoji,
            category: args.category,
            dueDate,
            status: "upcoming",
            recurrence: "none",
            isAutoGenerated: true,
            createdAt: now,
            updatedAt: now,
          });
        }
      }
    } else if (args.linkedLivestockCostTemplateId) {
      const template = await ctx.db.get(args.linkedLivestockCostTemplateId);
      if (template) {
        for (const stage of template.stages) {
          const dueDate = args.startDate + stage.weekFromStart * 7 * 24 * 60 * 60 * 1000;
          await ctx.db.insert("farmPlannerTasks", {
            farmerId: args.farmerId,
            seasonPlanId: planId,
            taskName: stage.stageName,
            emoji: stage.emoji,
            category: args.category,
            dueDate,
            status: "upcoming",
            recurrence: "none",
            isAutoGenerated: true,
            createdAt: now,
            updatedAt: now,
          });
        }
      }
    }

    return planId;
  },
});

/** Update season plan status */
export const updateSeasonPlanStatus = mutation({
  args: {
    planId: v.id("farmSeasonPlans"),
    requestingUserId: v.id("users"),
    status: v.union(
      v.literal("planning"),
      v.literal("active"),
      v.literal("completed"),
      v.literal("abandoned")
    ),
    notes: v.optional(v.string()),
  },
  handler: async (ctx, args): Promise<void> => {
    const plan = await ctx.db.get(args.planId);
    if (!plan) throw new Error("Plan not found");
    if (plan.farmerId !== args.requestingUserId) throw new Error("Not authorised");
    await ctx.db.patch(args.planId, { status: args.status, notes: args.notes, updatedAt: getUgandaTime() });
  },
});

/** Delete a season plan and its auto-generated tasks */
export const deleteSeasonPlan = mutation({
  args: {
    planId: v.id("farmSeasonPlans"),
    requestingUserId: v.id("users"),
  },
  handler: async (ctx, args): Promise<void> => {
    const plan = await ctx.db.get(args.planId);
    if (!plan) throw new Error("Plan not found");
    if (plan.farmerId !== args.requestingUserId) throw new Error("Not authorised");
    // Delete auto-generated tasks for this plan
    const tasks = await ctx.db
      .query("farmPlannerTasks")
      .withIndex("by_season_plan", (q: any) => q.eq("seasonPlanId", args.planId))
      .collect();
    for (const task of tasks.filter((t) => t.isAutoGenerated)) {
      await ctx.db.delete(task._id);
    }
    await ctx.db.delete(args.planId);
  },
});

// ─── TASKS ───────────────────────────────────────────────────────────────────

/** List tasks for a farmer (with optional status/season filters) */
export const listTasks = query({
  args: {
    farmerId: v.id("users"),
    status: v.optional(v.union(
      v.literal("upcoming"),
      v.literal("done"),
      v.literal("overdue"),
      v.literal("skipped")
    )),
    seasonPlanId: v.optional(v.id("farmSeasonPlans")),
  },
  handler: async (ctx, args) => {
    const now = Date.now();
    let rows: any[];
    if (args.seasonPlanId) {
      rows = await ctx.db
        .query("farmPlannerTasks")
        .withIndex("by_season_plan", (q: any) => q.eq("seasonPlanId", args.seasonPlanId))
        .collect();
    } else if (args.status) {
      rows = await ctx.db
        .query("farmPlannerTasks")
        .withIndex("by_farmer_status", (q: any) => q.eq("farmerId", args.farmerId).eq("status", args.status))
        .order("desc")
        .collect();
    } else {
      rows = await ctx.db
        .query("farmPlannerTasks")
        .withIndex("by_farmer", (q: any) => q.eq("farmerId", args.farmerId))
        .order("desc")
        .collect();
    }
    // Compute overdue: upcoming tasks past dueDate
    return rows.map((task) => ({
      ...task,
      isOverdue: task.status === "upcoming" && task.dueDate < now,
    }));
  },
});

/** Create a task (standalone or under a season plan) */
export const createTask = mutation({
  args: {
    farmerId: v.id("users"),
    seasonPlanId: v.optional(v.id("farmSeasonPlans")),
    taskName: v.string(),
    emoji: v.optional(v.string()),
    category: v.union(v.literal("crop"), v.literal("livestock"), v.literal("general")),
    dueDate: v.number(),
    recurrence: v.union(
      v.literal("none"),
      v.literal("daily"),
      v.literal("weekly"),
      v.literal("monthly")
    ),
    linkedUnitId: v.optional(v.id("farmTrackedUnits")),
    notes: v.optional(v.string()),
  },
  handler: async (ctx, args): Promise<Id<"farmPlannerTasks">> => {
    const now = getUgandaTime();
    return await ctx.db.insert("farmPlannerTasks", {
      farmerId: args.farmerId,
      seasonPlanId: args.seasonPlanId,
      taskName: args.taskName,
      emoji: args.emoji,
      category: args.category,
      dueDate: args.dueDate,
      status: "upcoming",
      recurrence: args.recurrence,
      linkedUnitId: args.linkedUnitId,
      notes: args.notes,
      isAutoGenerated: false,
      createdAt: now,
      updatedAt: now,
    });
  },
});

/** Mark task done. If recurrence != "none", auto-creates next task. */
export const completeTask = mutation({
  args: {
    taskId: v.id("farmPlannerTasks"),
    requestingUserId: v.id("users"),
  },
  handler: async (ctx, args): Promise<void> => {
    const task = await ctx.db.get(args.taskId);
    if (!task) throw new Error("Task not found");
    if (task.farmerId !== args.requestingUserId) throw new Error("Not authorised");
    const now = getUgandaTime();
    await ctx.db.patch(args.taskId, { status: "done", completedAt: now, updatedAt: now });
    // Auto-generate next recurring task
    if (task.recurrence !== "none") {
      const offsets: Record<string, number> = { daily: 1, weekly: 7, monthly: 30 };
      const days = offsets[task.recurrence] ?? 7;
      const nextDueDate = task.dueDate + days * 24 * 60 * 60 * 1000;
      await ctx.db.insert("farmPlannerTasks", {
        farmerId: task.farmerId,
        seasonPlanId: task.seasonPlanId,
        taskName: task.taskName,
        emoji: task.emoji,
        category: task.category,
        dueDate: nextDueDate,
        status: "upcoming",
        recurrence: task.recurrence,
        linkedUnitId: task.linkedUnitId,
        notes: task.notes,
        isAutoGenerated: true,
        createdAt: now,
        updatedAt: now,
      });
    }
  },
});

/** Skip or reschedule a task */
export const skipTask = mutation({
  args: {
    taskId: v.id("farmPlannerTasks"),
    requestingUserId: v.id("users"),
  },
  handler: async (ctx, args): Promise<void> => {
    const task = await ctx.db.get(args.taskId);
    if (!task) throw new Error("Task not found");
    if (task.farmerId !== args.requestingUserId) throw new Error("Not authorised");
    await ctx.db.patch(args.taskId, { status: "skipped", updatedAt: getUgandaTime() });
  },
});

/** Delete a task */
export const deleteTask = mutation({
  args: {
    taskId: v.id("farmPlannerTasks"),
    requestingUserId: v.id("users"),
  },
  handler: async (ctx, args): Promise<void> => {
    const task = await ctx.db.get(args.taskId);
    if (!task) throw new Error("Task not found");
    if (task.farmerId !== args.requestingUserId) throw new Error("Not authorised");
    await ctx.db.delete(args.taskId);
  },
});

/** Get calendar view: tasks grouped by date for a date range */
export const getCalendarTasks = query({
  args: {
    farmerId: v.id("users"),
    fromDate: v.number(), // timestamp start of range
    toDate: v.number(),   // timestamp end of range
  },
  handler: async (ctx, args): Promise<Record<string, any[]>> => {
    const tasks = await ctx.db
      .query("farmPlannerTasks")
      .withIndex("by_farmer", (q: any) => q.eq("farmerId", args.farmerId))
      .collect();
    const inRange = tasks.filter((t) => t.dueDate >= args.fromDate && t.dueDate <= args.toDate);
    const now = Date.now();
    const grouped: Record<string, any[]> = {};
    for (const task of inRange) {
      const date = new Date(task.dueDate);
      const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
      if (!grouped[key]) grouped[key] = [];
      grouped[key].push({ ...task, isOverdue: task.status === "upcoming" && task.dueDate < now });
    }
    return grouped;
  },
});
